site_name: 'AutoOrtho Continued'
repo_url: https://github.com/ProgrammingDinosaur/autoortho4xplane
theme:
  name: 'material'
  features:
    - navigation.tabs
  palette:
    scheme: slate

extra:
  version:
    provider: mike

