- module-name: 'autoortho'
  dlls:
    - from_filenames:
        relative_path: 'lib/macos'
        prefixes: ['libispc_texcomp', 'libstbdxt']
        suffixes: ['dylib']
        when: 'macos'
    - from_filenames:
        relative_path: 'aoimage' 
        prefixes: ['aoimage']
        suffixes: ['dylib']
        when: 'macos'

    - from_filenames:
        relative_path: 'lib/linux'
        prefixes: ['libispc_texcomp', 'lib_stb_dxt']
        suffixes: ['so']
        when: 'linux'
    - from_filenames:
        relative_path: 'aoimage'
        prefixes: ['aoimage']
        suffixes: ['so']
        when: 'linux'

    - from_filenames:
        relative_path: 'lib/windows'
        prefixes: ['ispc_texcomp', 'stb_dxt']
        suffixes: ['dll']
        when: 'win32'
    - from_filenames:
        relative_path: 'aoimage'
        prefixes: ['aoimage']
        suffixes: ['dll']
        when: 'win32'
    - from_filenames:
        relative_path: 'lib/windows/7zip'
        prefixes: ['7za', '7zxa']
        suffixes: ['dll']
        when: 'win32'
    - from_filenames:
        relative_path: 'lib/windows'
        prefixes: ['DSFTool']
        suffixes: ['exe']
        executable: yes
        when: 'win32'
    - from_filenames:
        relative_path: 'lib/windows/7zip'
        prefixes: ['7za']
        suffixes: ['exe']
        executable: yes
        when: 'win32'

  data-files:
    - dirs:
        - 'lib/macos/7zip'
        - 'lib/macos'
      patterns:
        - '7zz'
        - 'DSFTool'
      when: 'macos'

    - dirs:
        - 'lib/linux/7zip'
        - 'lib/linux'
      patterns:
        - '7zz'
        - 'DSFTool'
      when: 'linux'